### ISSUE TITLE
stavefejl

### ISSUE THREAD

**Issue by EjlersenKL** [hl7dk/kl-children#10]
https://build.fhir.org/ig/hl7dk/kl-children/branches/aims/Questionnaire-klgateway-children-aims.html#scope-and-usage

KLGatewayChildrenADBB is used to define the Alberta Infant Motor Scale (AIMS).

og 

The link-ids from this questionnaire have to be referred in the QuestionnaireResponse, that holds the answers to an ADBB questionnaire.

Ved godt det måske blot er fordi, vi her stadig har med et eksempel at gøre :)

**Comment by Kirstinerosenbeck** [comment]
rettet
