### ISSUE TITLE
lidt anderledes udlæg af absentReason

### ISSUE THREAD

**Issue by EjlersenKL** [hl7dk/kl-children#11]
https://build.fhir.org/ig/hl7dk/kl-children/branches/aims/StructureDefinition-klgateway-children-indicator.html#scope-and-usage

Jeg er usikker på om nedenstående henvender sig til udviklere eller brugere:

To indicate missing data, Observation.dataAbsentReason is used. Observation.dataAbsentReason is mandatory if no value is given. Use the appropriate value according to the FHIR standard, or choose value ‘unknown’ if in doubt.

Jeg synes vi tidligere har formuleret det "mere frivilligt" at tilknytte forskellige værdier ifm. dataAbsent

**Comment by Kirstinerosenbeck** [comment]
rette i denne og i feeding ressourcen
