### ISSUE TITLE
related parent

### ISSUE THREAD

**Issue by EjlersenKL** [hl7dk/kl-children#13]
https://build.fhir.org/ig/hl7dk/kl-children/branches/aims/StructureDefinition-klgateway-children-related-parent.html#scope-and-usage 

Jeg synes den er lidt svær at forstå og få greb om. Jeg tror dog det skyldes manglende indsigter fra min side. Prøvede at putte den via chatGPT og forstår det stadig ikke helt. Men måske vi kan verficere og/eller bruge dele af bottens alternative forslag:

KLGatewayChildrenRelatedParent identifies the relationship between a child and their parents. Include Citizen and RelatedPerson resources for the parents only when relevant to the child’s report.

In this implementation:

- RelatedPerson.patient refers to the child.
- RelatedPerson.relationship contains a code that specifies the relationship type. In this guide, the relationship code is always 'PRN' for parent.

It might seem unusual that this resource lacks a CPR identifier or other identifiers. However, such identifiers are stored in the Citizen resource of the parent, which links back to the RelatedPerson resource. Therefore, duplicating this information in the RelatedPerson resource is unnecessary.

The RelatedPerson.active attribute is optional and assumed to be true unless otherwise specified. Setting RelatedPerson.active to false should only be used to indicate that the entry was made in error and that the relationship does not exist in the municipal system and should not have been recorded.

**Comment by Kirstinerosenbeck** [comment]
Description changed.
