### ISSUE TITLE
Formulering forside dataabsent

### ISSUE THREAD

**Issue by EjlersenKL** [hl7dk/kl-children#7]
The applied rules mean that an observation without a value must be reported if one of the mentioned encounters are completed without the data being obtained, and an appropriate dataAbsentReason must be given

alternativt forslag:
When an encounter is completed without obtaining the a mandatory observations, the rules require that an observation be reported and given a 'dataAbsentReason'.

https://build.fhir.org/ig/hl7dk/kl-children/branches/aims/#special-constraints-and-resulting-reporting-practises

**Comment by Kirstinerosenbeck** [comment]
rettet
