### ISSUE TITLE
formulering, forsinket dokumentation

### ISSUE THREAD

**Issue by EjlersenKL** [hl7dk/kl-children#8]
forslag til alternativ formulering:

Be aware that reporting challenges may arise if documentation is completed in the days after a visit. If a report lacks mandatory observations, you should attempt to submit the record within the next two days to check if documentation has been completed. If the data remains undocumented by the end of the second day, report the observations immediately without a value and provide an appropriate 'dataAbsentReason'.

**Comment by Kirstinerosenbeck** [comment]
rettet
